version: '3.8'

services:
  seed:
    image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/seed
    container_name: seed
    build:
      context: ./seed-data
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - my_network

  nginx:
    image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/nginx-lb
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - vote
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - my_network

  worker:
    image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/worker
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    networks:
      - my_network

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  vote:
    image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/vote
    build:
      context: ./vote
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    networks:
      - my_network

  result:
    image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/result
    container_name: result
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    external: true