apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: seed
          image: europe-west9-docker.pkg.dev/calcium-post-453513-b5/voting-image/seed
          imagePullPolicy: Always
      restartPolicy: Never
